galaxy_info:
  author: Stephane Segning
  description: Common role for all machines
  company: adorsys GmbH & Co. KG
  license: MIT

  min_ansible_version: 2.1

  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Debian
    - name: Ubuntu
    - name: MacOSX

  galaxy_tags:
    - zsh
    - git
    - homebrew
    - omz
    - curl
    - wget

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
