---
# roles/common/tasks/homebrew.yml

- name: Check if Homebrew is installed
  shell: command -v brew
  register: brew_installed
  ignore_errors: yes
  changed_when: false

- name: Install Homebrew
  shell: |
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: brew_installed.rc != 0
