galaxy_info:
  author: Stephane Segning
  description: Role to install sdkman
  company: adorsys GmbH & Co. KG
  license: MIT

  min_ansible_version: 2.1

  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Debian
    - name: Ubuntu
    - name: MacOSX

  galaxy_tags:
    - sdkman
    - java
    - gradle
    - maven
    - kotlin

dependencies:
  - name: gis.laptop.common