- name: Check if Docker is installed
  command: docker --version
  register: docker_installed
  changed_when: false
  ignore_errors: true

- name: Install Docker using the official Docker script
  ansible.builtin.shell:
    cmd: curl -fsSL https://get.docker.com | sh
  when: docker_installed.rc != 0
  become: yes
