- name: Fail if molecule group is missing
  hosts: localhost
  tasks:
    - name: Print some info
      ansible.builtin.debug:
        msg: "{{ groups }}"

    - name: Assert group existence
      ansible.builtin.assert:
        that: "'molecule' in groups"
        fail_msg: |
          molecule group was not found inside inventory groups: {{ groups }}

- name: Converge
  hosts: molecule
  gather_facts: true
  tasks:
    - name: Include common role
      include_role:
        name: common

    - name: Check if Zsh is installed
      command: zsh --version
      register: zsh_version
      changed_when: false
      ignore_errors: true

    - name: Assert Zsh is installed
      ansible.builtin.assert:
        that: zsh_version.rc == 0
        fail_msg: "Zsh is not installed"
