---
- name: Converge
  hosts: localhost
  gather_facts: true
  connection: local
  tasks:
    - name: Include docker role
      include_role:
        name: docker

    # Example validation tasks
    - name: Check if Docker is installed
      command: docker --version
      register: docker_version
      changed_when: false
      ignore_errors: true

    - name: Assert Docker is installed
      ansible.builtin.assert:
        that: docker_version.rc == 0
        fail_msg: "Docker is not installed"
