- name: Fail if molecule group is missing
  hosts: localhost
  tasks:
    - name: Print some info
      ansible.builtin.debug:
        msg: "{{ groups }}"

    - name: Assert group existence
      ansible.builtin.assert:
        that: "'molecule' in groups"
        fail_msg: |
          molecule group was not found inside inventory groups: {{ groups }}

- name: Converge
  hosts: molecule
  gather_facts: true
  tasks:
    - name: Include NodeJS role
      include_role:
        name: nodejs

    - name: Check if NVM is installed
      shell: |
        set -e
        export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm --version
      register: nvm_version
      changed_when: false
      ignore_errors: true

    - name: Assert NVM is installed
      ansible.builtin.assert:
        that: nvm_version.rc == 0
        fail_msg: "NVM is not installed"

    - name: Check if NodeJS is installed
      shell: |
        set -e
        export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        node --version
      register: node_version
      changed_when: false
      ignore_errors: true

    - name: Assert NodeJS is installed
      ansible.builtin.assert:
        that: node_version.rc == 0
        fail_msg: "Node is not installed"
